#!/bin/bash

cd /root

if [ -d "/root/.vim" ]
then
  echo "Directory /root/.vim exists."
else
  echo "Error: Directory /root/.vim does not exists."
  mkdir /root/.vim
  cd /root/.vim
fi

if [ -d "/root/.vim/colors" ]
then
  echo "Directory /root/.vim/colors exists."
  cd /root/
  git clone https://github.com/sickill/vim-monokai.git
  cp -v /root/vim-monokai/colors/monokai.vim /root/.vim/colors
  rm -rvf vim-monokai
else
  echo "Error: Directory /root/.vim does not exists."
  mkdir /root/.vim/colors
  cd /root/
  git clone https://github.com/sickill/vim-monokai.git
  cp -v /root/vim-monokai/colors/monokai.vim /root/.vim/colors
  rm -rvf vim-monokai
fi

cd /root
rm -rf myvimrc

cd /root
tee -a .bashrc << EOF
export VIMINIT='source ~/vim_setup/.vimrc'
export MYVIMRC='~/vim_setup/.vimrc'
EOF

cd /root
source /root/.bashrc
